---
# Preamble

## Author
author:
  name: Гелдиев Ыхлас
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 1032249184@pfur.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6
## Title
title: "Программный RAID"
subtitle: "RAID на основе BtrFS"
license: CC BY
date: 2026-12-06
## Generic options
lang: ru-RU
slide-level: 2
crossref:
  lof-title: Список иллюстраций
  lot-title: Список таблиц
  lol-title: Листинги
## Formats
format:
  ### Pdf output format
  beamer:
    include-in-header:
      text: |
        \usepackage{fontspec}
        \setmainfont{Noto Serif}
        \setsansfont{Noto Sans}
    toc: true
    toc-title: Содержание
    number-sections: true
    colorlinks: false
    toc-depth: 2
    slide-level: 2
    aspectratio: 169
    section-titles: true
    theme: metropolis
    themeoptions: progressbar=frametitle,sectionpage=progressbar,numbering=fraction
    #### Language
    babel-lang: russian
    babel-otherlangs: english
  ### Html output
  revealjs:
    transition: slide
    margin: 0.2
    smaller: false
    output-ext: html
    theme: beige
    logo: _resources/image/logo_rudn.png
---

# Информация

## Докладчик

- Гелдиев Ыхлас
- студент
- Российский университет дружбы народов им. П. Лумумбы
- [1032249184@pfur.ru](mailto:1032249184@pfur.ru)
- <https://geldiyevy.github.io/ru/>

# Вводная часть

## Эволюция хранения

- Традиционный стек: Слоистая архитектура (Диск -> RAID-контроллер -> LVM -> Файловая система)
- Смена парадигмы: BtrFS объединяет слои файловой системы и управления томами (Volume Manager).
- Ключевое отличие: Встроенный программный RAID, который "понимает" структуру данных, в отличие от "слепых" аппаратных контроллеров.

# RAID на основе BtrFS

## Архитектурные особенности

- Чанки (Chunks): Массив строится не поверх целых дисков, а на основе блоков (обычно 1 ГБ), распределенных по дискам.

- Раздельные профили Возможность задавать разный уровень RAID для метаданных (критично) и самих данных (скорость)

- Геометрия: Поддержка дисков разного объема в одном массиве с полным использованием пространства (в отличие от классического RAID).

## Уровни RAID и специфика

- RAID 1 в BtrFS: Это не зеркало дисков, а правило "хранить 2 копии блока на разных устройствах" (даже если дисков 3 или 5)

- RAID 1с3/1с4: Новые профили (ядро 5.5+) для хранения 3-х и 4-х копий данных для защиты от ошибок чтения (URE) на больших дисках.

- RAID 5/6: Формально поддерживаются, но имеют статус "Unstable"(нестабильно) для продакшена.

## Преимущества интеграции:

- Self-healing (Самовосстановление): Автоматическое обнаружение и исправления "тихих" ошибок (bit rot) за счет контрольных сумм (Checksums)

- Онлайн-трансформация: Добавление/удаление дисков и смена уровня RAID (например, с 1 на 5) на живой системе без даунтайма

- Снэпшоты: Мгновенные и атомарные снимки состояния всего массива благодаря CoW-архитектуре

## Проблемы: Write Hole (Дыра записи)

- Суть проблемы: При сбое питания во время записи в RAID 5/6 данные и блок четности могут рассинхронизироваться.

- Отличие от Hardware RAID: В программном RAID нет энергонезависимой памяти (NVRAM) или батарейки (BBU) для защиты транзакции.

- Рекомендации: Использовать BtrFS только в режимах RAID 1, 10 или 1c3; для четности (RAID 5/6) выбирать ZFS или mdadm

# Заключение

## Выводы

- Тренд: Переход от аппаратных контроллеров к умным файловым системам м глубокой интеграцией.

- Надежность: BtrFS RAID 1/10 обеспечивает лучшую целостность данных за счет хеширования, чем классический RAID.

- Итог: Мощный инструмент для архитектора ОС, но требующий понимания ограничений (избегать RAID 5/6)
